apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: use-eks
  region: us-east-1
  version: "1.33"
vpc:
  id: "${USE_VPC_ID}"
  subnets:
    private:
      us-east-1a:
        id: "${USE_PRIVATE_SUBNET_AZA}"
      us-east-1b:
        id: "${USE_PRIVATE_SUBNET_AZB}"
managedNodeGroups:
  - name: ng-main
    instanceType: t4g.2xlarge
    desiredCapacity: 8
    minSize: 8
    maxSize: 8
    volumeSize: 100
    volumeType: gp3
    amiFamily: AmazonLinux2023
    iam:
      instanceRoleARN: "${USE_EKS_NODE_ROLE_ARN}"
cloudWatch:
  clusterLogging:
    enableTypes:
      - api
      - audit
      - authenticator
      - controllerManager
      - scheduler
secretsEncryption:
  keyARN: "${USE_EKS_SECRETS_KEY_ARN}"
addons:
  - name: vpc-cni
  - name: coredns
  - name: kube-proxy
  - name: aws-ebs-csi-driver
  - name: aws-efs-csi-driver
  - name: eks-pod-identity-agent
  - name: amazon-cloudwatch-observability
  - name: aws-load-balancer-controller
    version: v3.1.0
  - name: karpenter
    version: v1.9.0
